# AI-KMS Microservices - Local Development
# This is a stub configuration - no images will be pulled during Phase 1

version: '3.8'

services:
  # API Gateway - Public edge service
  api-gateway:
    # build: ../services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # depends_on: [auth-svc, doc-ingest-svc, embedding-svc, search-svc, agent-svc]

  # Authentication Service
  auth-svc:
    # build: ../services/auth-svc
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}

  # Document Ingestion Service
  doc-ingest-svc:
    # build: ../services/doc-ingest-svc
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development

  # Embedding Service
  embedding-svc:
    # build: ../services/embedding-svc
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER}

  # Search Service
  search-svc:
    # build: ../services/search-svc
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=development

  # Agent Service
  agent-svc:
    # build: ../services/agent-svc
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
      - AI_PROVIDER=${AI_PROVIDER}

  # CSAT Service
  csat-svc:
    # build: ../services/csat-svc
    ports:
      - "3006:3000"
    environment:
      - NODE_ENV=development

  # Realtime Service
  realtime-svc:
    # build: ../services/realtime-svc
    ports:
      - "3007:3000"
    environment:
      - NODE_ENV=development

  # LINE Bridge Service
  line-bridge-svc:
    # build: ../services/line-bridge-svc
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=development

  # NLP Service (Python)
  nlp-svc:
    # build: ../services/nlp-svc
    ports:
      - "8000:8000"
    environment:
      - PYTHON_ENV=development

  # Admin UI (Frontend)
  admin-ui:
    # build: ../apps/admin-ui
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

networks:
  default:
    name: ai-kms-network