openapi: 3.1.0
info:
  title: search-svc
  version: 0.0.1
servers:
  - url: http://localhost

paths:
  /healthz:
    get:
      summary: Liveness check
      responses:
        "200":
          description: OK

  /readyz:
    get:
      summary: Readiness check
      responses:
        "200":
          description: Ready

  /search:
    post:
      summary: Hybrid search
      responses:
        "200":
          description: Search results
        "400":
          description: Invalid query

components:
  schemas:
    Error:
      $ref: "../common/schemas.yaml#/components/schemas/Error"