openapi: 3.1.0
info:
  title: auth-svc
  version: 0.0.1
servers:
  - url: http://localhost

paths:
  /healthz:
    get:
      summary: Liveness check
      responses:
        "200":
          description: OK

  /readyz:
    get:
      summary: Readiness check
      responses:
        "200":
          description: Ready

  /login:
    post:
      summary: User login
      responses:
        "200":
          description: Login successful
        "401":
          description: Authentication failed

  /register:
    post:
      summary: User registration
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid input
        "409":
          description: User already exists

  /refresh:
    post:
      summary: Refresh token
      responses:
        "200":
          description: Token refreshed
        "401":
          description: Invalid refresh token

  /validate:
    post:
      summary: Validate token
      responses:
        "200":
          description: Token is valid
        "401":
          description: Invalid token

  /me:
    get:
      summary: Get current user
      responses:
        "200":
          description: Current user info
        "401":
          description: Not authenticated

  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User found
        "404":
          description: User not found

  /profile:
    put:
      summary: Update user profile
      responses:
        "200":
          description: Profile updated
        "401":
          description: Not authenticated

components:
  schemas:
    Error:
      $ref: "../common/schemas.yaml#/components/schemas/Error"
    User:
      $ref: "../common/schemas.yaml#/components/schemas/User"