openapi: 3.1.0
info:
  title: agent-svc
  version: 0.0.1
servers:
  - url: http://localhost

paths:
  /healthz:
    get:
      summary: Liveness check
      responses:
        "200":
          description: OK

  /readyz:
    get:
      summary: Readiness check
      responses:
        "200":
          description: Ready

  /chat:
    post:
      summary: AI chat
      responses:
        "200":
          description: Chat response
        "400":
          description: Invalid message

  /eval:
    post:
      summary: Run evaluation
      responses:
        "200":
          description: Evaluation results
        "400":
          description: Invalid evaluation

components:
  schemas:
    Error:
      $ref: "../common/schemas.yaml#/components/schemas/Error"
    Message:
      $ref: "../common/schemas.yaml#/components/schemas/Message"